### ISSUE TITLE
OSM Data tiles is stored in tilescache

### ISSUE THREAD

**Issue by juanmanuelrq** [MKuranowski/pyroutelib3#12]
Hi, how can I download the .osm file?

**Comment by MKuranowski** [comment]
That's out of the scope of `pyroutelib3` — :confused: what do you mean?

.osm is an extension of a _file format_, look at https://wiki.openstreetmap.org/wiki/OSM_XML.

You can download parts of data produced by OpenStreetMap Contributors (vide https://www.openstreetmap.org/) from https://download.geofabrik.de/index.html — but that should be done automatically by the script.

But you can also create your own .osm data and plug it into pyroutelib, that's what the `localfile` argument of datastore is for.

**Comment by MKuranowski** [comment]
Closing, no response was given in a month, and I don't see a pyroutelib3 bug here.
