### ISSUE TITLE
indent error?

### ISSUE THREAD

**Issue by git-bone** [MKuranowski/pyroutelib3#14]
hi, 

is it possible that something is wrong on https://github.com/MKuranowski/pyroutelib3/blob/master/pyroutelib3.py#L517. I seem to think that that should move up 4 spaces?

kind regards

**Comment by MKuranowski** [comment]
No, it's okey. `else` statements on loops are executed if a `break` was not reached.

See <https://docs.python.org/3/tutorial/controlflow.html#break-and-continue-statements-and-else-clauses-on-loops>.
