### ISSUE TITLE
pbf support

### ISSUE THREAD

**Issue by git-bone** [MKuranowski/pyroutelib3#15]
Hi, 
Are you by any chance working on pbf file support? 

Thanks!

Kind regards

**Comment by MKuranowski** [comment]
I didn't have that in mind, but I can try to add a solution.
It might take some time, so a PR would be welcome on that.

**Comment by git-bone** [comment]
I might have a try at it. Found a lib https://github.com/osmcode/pyosmium that might do the trick

**Comment by MKuranowski** [comment]
Hello, some info on this:

I tried using several libraries and none of them seem to work properly.
- [pyosmium](https://github.com/osmcode/pyosmium) causes seg faults when trying to test anything with it
- [osmread](https://github.com/dezhin/osmread) can't even read plain OSM XML files I use (opened a PR there, no response)
- [imposm-parser](https://github.com/omniscale/imposm-parser) is deprecated and does not support Python 3.

Maybe if there's any other nice library — it could be wired up to pyroutelib3, but as of now we're stuck with XML files only.

**Comment by MKuranowski** [comment]
Added support in 1.5.1, see the Datastore wiki on arguments localfile and localfileType.
