### ISSUE TITLE
Support for highway=living_street

### ISSUE THREAD

**Issue by m0nac0** [MKuranowski/pyroutelib3#20]
Currently, if a route starts at a road tagged as [highway=living_street](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dliving_street), a node on another nearby road is selected as starting node. Instead, living roads should be navigable, but with a high cost, as one typically has to drive slowly there.

**Comment by MKuranowski** [comment]
Thanks for spotting that! Will add living_street for bicycles, cars and on-foot

**Comment by MKuranowski** [comment]
Added in https://github.com/MKuranowski/pyroutelib3/commit/19237ad91426dd25040ce330af69d26ef849d7c7 , pushed in 1.6.2.
