### ISSUE TITLE
about restriction of the day and hour

### ISSUE THREAD

**Issue by guyanf** [MKuranowski/pyroutelib3#21]
When I use the restriction, I add  relation like these:
`
  <relation id="1678" uid="1678">
    <member type="way" ref="807931" role="from"/>
    <member type="way" ref="807930" role="via"/>
    <member type="way" ref="787860" role="via"/>
    <member type="way" ref="787862" role="via"/>
    <member type="way" ref="789022" role="to"/>
    <tag k="restriction" v="no_left_turn"/>
    <tag k="day_on" v="Monday"/>
    <tag k="day_off" v="Friday"/>
    <tag k="hour_on" v="07:00"/>
    <tag k="hour_off" v="09:00"/>
    <tag k="type" v="restriction"/>
  </relation>
`
So the path of the route is restricted all day.I didn't known the reason. The current time is 14:00.

**Comment by guyanf** [comment]
When I change the code, the restriction didn't work. 
`
 <relation id="1678" uid="1678">
    <member type="way" ref="807931" role="from"/>
    <member type="way" ref="807930" role="via"/>
    <member type="way" ref="787860" role="via"/>
    <member type="way" ref="787862" role="via"/>
    <member type="way" ref="789022" role="to"/>
    <tag k="restriction:conditional" v="no_left_turn @ (Mo-Fr 07:00-09:30,15:30-17:30)"/>
    <tag k="type" v="restriction"/>
  </relation>`

>

**Comment by MKuranowski** [comment]
The Graph doesn't take time into account anywhere, so conditional anything makes no sense.

Taking current system time to process conditional restrictions is a bad idea, as:
  a) Graph may represent data in a different timezone to system timezone.  
  b) Graphs would have to be recreated as soon as a conditional feature turns off/on.
  c) Assuming that users would want routes valid as-of-graph-creation is a big assumption, and basically all my use cases violate such assumption.

The proper way would be to handle time in `doRoute()`, but to be honest, I don't have the time and energy to code anything that could properly handle conditional features. You can try to make a PR that would do that, but remember that pyroutelib3 is meant to be a simple (but modified) A* implementation, **not** a full-fledged routing engine.

My current recommendation would be to pre-process the OSM file and remove any conditional features that you think shouldn't be applied, and remove the conditionality from features that you think should apply (e.g. `<tag k="restriction:conditional" v="no_left_turn @ (Mo-Fr 07:00-09:30,15:30-17:30)"/>` → `<tag k="restriction" v="no_left_turn"/>`).

**Comment by guyanf** [comment]
Hi guys!
I known the reason, thanks.

Now, I try converting my data to osm, and used to route plan.
