### ISSUE TITLE
KeyError when restriction not in rel tag

### ISSUE THREAD

**Issue by tanguy-launay** [MKuranowski/pyroutelib3#24]
When a specific transport mode (like car) is selected, sometimes the route appears to have no restriction but the datastore storeRestriction function tries to check it out.

However, by doing so, it produces an error because _rel tag_ dictionary has no **restriction** keyword (line 252) (in fact the bug only happens when another restriction exists like **restriction:bicycle** keyword is present).
A simple verification could be implemented:
```
        elif rel["tag"].get("restriction"):
            restrType = rel["tag"]["restriction"]
        else:
            return False
```

https://github.com/MKuranowski/pyroutelib3/blob/749b51e9a741310a2679910de72a2526ef1ca761/pyroutelib3/datastore.py#L252

**Comment by MKuranowski** [comment]
This is guarded by this check:

https://github.com/MKuranowski/pyroutelib3/blob/9c5500f29a163c388e24bbcee130b25ab9cffad6/pyroutelib3/datastore.py#L170

The assumption is that if a relation has tag `type=restriction`, then it must have a `restriction=…` tag; if it has `type=restriction:transport_type`, it must have either `restriction` or a `restriction:transport_type` tag.

Though I guess that breaks on conditional restrictions, which just don't make sense for a timeless graph, as used here.

I've added a more clear `OsmInvalidRestriction` in that case, which are by default ignored.
