### ISSUE TITLE
Cycle route issues

### ISSUE THREAD

**Issue by vutle** [MKuranowski/pyroutelib3#25]
Why does the cycle take a long path instead of a short path?
Example below use "cycle" as the option.

![image](https://user-images.githubusercontent.com/6241928/121940517-89283e00-cd91-11eb-8e80-dd7996e6dcda.png)
![image](https://user-images.githubusercontent.com/6241928/121940580-9e04d180-cd91-11eb-994e-4d7cdf3d5796.png)

**Comment by MKuranowski** [comment]
Depends on the route types, but the current weights heavily prefer highway=residential and highway=cycleway over highway=primary or highway=secondary.

https://github.com/MKuranowski/pyroutelib3/blob/master/pyroutelib3/types.py#L93

You can tweak those weights and if you think you've found something better, open a PR - but for now imma close this issue, as that seems like a correct result _given the current settings_.

**Comment by vutle** [comment]
Are you using the same weight like other route engine?  Like ORS  or OSRM?

Regards,
Vu

**Comment by MKuranowski** [comment]
Please see the attached line of code
