### ISSUE TITLE
Possibility to change SEARCH_LIMIT

### ISSUE THREAD

**Issue by PositivPy** [MKuranowski/pyroutelib3#27]
I encountered the problem when using your library with Django: the request and server would hang forever because the SEARCH_LIMIT is set to 1M. Modifying the source code with a 100K limit did the trick. 

It would be great if you could add this as an argument to the router/DataStore.

**Comment by MKuranowski** [comment]
```python
import pyroutelib3.util
pyroutelib3.util.SEARCH_LIMIT = 100_000
```

Should do the trick, tough modifying what are essentially constants isn't perfect practice.
