### ISSUE TITLE
 unclosed token error

### ISSUE THREAD

**Issue by IssaIssa1** [MKuranowski/pyroutelib3#3]
I am getting the following error when trying to generate some routes, I am using python 3.6 on Windows 10

```
Traceback (most recent call last):
  File .../Desktop/distnace comparison.py", line 11, in <module>
    status, route = router.doRoute(start, end)
  File ...\AppData\Local\Programs\Python\Python36\lib\site-packages\pyroutelib3\__init__.py", line 373, in doRoute
    self._addToQueue(x,i,nextItem, weight)
  File ...\AppData\Local\Programs\Python\Python36\lib\site-packages\pyroutelib3\__init__.py", line 388, in _addToQueue
    self.data.getArea(end_pos[0], end_pos[1])
  File ...\AppData\Local\Programs\Python\Python36\lib\site-packages\pyroutelib3\__init__.py", line 119, in getArea
    return(self.loadOsm(filename))
  File ...\AppData\Local\Programs\Python\Python36\lib\site-packages\pyroutelib3\__init__.py", line 216, in loadOsm
    data = self.parseOsmFile(filename)
  File ...\AppData\Local\Programs\Python\Python36\lib\site-packages\pyroutelib3\__init__.py", line 178, in parseOsmFile
    for event, elem in etree.iterparse(f): # events=['end']
  File ...\AppData\Local\Programs\Python\Python36\lib\xml\etree\ElementTree.py", line 1227, in iterator
    root = pullparser._close_and_return_root()
  File ...\AppData\Local\Programs\Python\Python36\lib\xml\etree\ElementTree.py", line 1274, in _close_and_return_root
    root = self._parser.close()
  File "<string>", line None
xml.etree.ElementTree.ParseError: unclosed token: line 586, column 1
```

**Comment by MKuranowski** [comment]
It looks like something is wrong with the OSM file…
Are you using your own .OSM?

**Comment by IssaIssa1** [comment]
hey thanks for the quick reply, 
No I am not,

**Comment by MKuranowski** [comment]
You actually caught me when I am on my PC :smiley:.

Well, it should be something with OSM data then.
Have you tried cleaning the tilescache/ folder?

I'm not able to reproduce it, so do you mind sharing data on route that causes the error? Like `start` and `end` or lat-longs of start and end points…

**Comment by IssaIssa1** [comment]
I just tried cleaning the tilescache, didnt work :/
Please find the lat-lons I am using; I am generating random routes and I am trying to find their length (distance) with another customized function. I tried Open Street Maps and Google Maps websites to check if the route exists, and it does for both.

```
router = Router("car")
start = router.data.findNode(39.701196, -106.678114)
end = router.data.findNode(39.601328, -107.167394)
```

**Comment by MKuranowski** [comment]
Still no luck reproducing :/
The traceback shows an issue with reading the OSM data, so it's probably an issue in them.

---

But actually, auto-download pyroutelib3 doesn't work well on longer distances: the amount of tiles it downloads skyrockets…

When working on larger distances, I'd actually recommend downloading the OSM on your hand, you can do that with Overpass API.
I used this query around the cooridnates you've given:
```
[bbox:39.592740,-107.181204,39.732175,-106.636801][out:xml];(way["highway"="motorway"];way["highway"="motorway_link"];way["highway"="trunk"];way["highway"="trunk_link"];way["highway"="primary"];way["highway"="primary_link"];way["highway"="secondary"];way["highway"="secondary_link"];way["highway"="tertiary"];way["highway"="tertiary_link"];way["highway"="unclassified"];way["highway"="minor"];way["highway"="residential"];way["highway"="service"];);(._;>;);out;
```
You can find your bbox on http://bboxfinder.com/, (but remeber to switch to Lat / Long format!), then you can check the Overpass query at https://overpass-turbo.eu/. Once you're happy with the query, URL Encode it (with for exmaple https://meyerweb.com/eric/tools/dencoder/) — then the XML file can be downloaded at
**https://overpass-api.de/api/interpreter?data=<URL_ENCODED_QUERY>**. In mine exmaple this would is:
```
https://overpass-api.de/api/interpreter?data=%5Bbbox%3A39.592740%2C-107.181204%2C39.732175%2C-106.636801%5D%5Bout%3Axml%5D%3B(way%5B%22highway%22%3D%22motorway%22%5D%3Bway%5B%22highway%22%3D%22motorway_link%22%5D%3Bway%5B%22highway%22%3D%22trunk%22%5D%3Bway%5B%22highway%22%3D%22trunk_link%22%5D%3Bway%5B%22highway%22%3D%22primary%22%5D%3Bway%5B%22highway%22%3D%22primary_link%22%5D%3Bway%5B%22highway%22%3D%22secondary%22%5D%3Bway%5B%22highway%22%3D%22secondary_link%22%5D%3Bway%5B%22highway%22%3D%22tertiary%22%5D%3Bway%5B%22highway%22%3D%22tertiary_link%22%5D%3Bway%5B%22highway%22%3D%22unclassified%22%5D%3B%5B%22highway%22%3D%22minor%22%5D%3B%5B%22highway%22%3D%22residential%22%5D%3B%5B%22highway%22%3D%22service%22%5D%3B)%3B(._%3B%3E%3B)%3Bout%3B%0A
```

You can either save it to your disk and initialise the Router like that
```python3
from pyroutelib3 import Router
router = Router("car", "<path-to-downloaded-file>")
      ⋮
```
Or if you want to automatiucally download the new file, just use [Requests](http://docs.python-requests.org/en/master/) and [tempfile.NamedTemporaryFile](https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile) (with delete=False).

**Comment by IssaIssa1** [comment]
thanks this was helpful

**Comment by filclem** [comment]
Hi,
may be a bug ?
I've got a problem with these adresses and only these (foot or car also and first time unclosed token error) :
```
coor_depart = [ 50.72046, 1.61538]      
coor_arrivee= [50.72712, 1.60874]   
router = Router("foot")
depart = router.findNode(coor_depart[0], coor_depart[1])
arrivee = router.findNode(coor_arrivee[0], coor_arrivee[1])
status, route = router.doRoute(depart, arrivee)
```
----------
in the folder : tilescache , files are created without end (exemple :
![Capture du 2019-04-09 12-08-18](https://user-images.githubusercontent.com/24918579/55800025-0598a580-5ad3-11e9-859f-98eae5813e3f.png)
---------
with a osm file in the folder, it stop (a little box including the points) but with no issue.
---------
i'm just testing it again,  unclosed token error message again !

**Comment by MKuranowski** [comment]
Please post a traceback, I kinda don't know what you're talking about 😕

But, like a said previously
_The traceback shows an issue with reading the OSM data, so it's probably an issue in them._

Unclosed Token Error is raised by the XML ETree parser, not by pyroutelib3.

Like I mentioned earlier, it's better to handle OSM data on your own. Can you try reproducing it when using your own .osm file?
