### ISSUE TITLE
Redefine transport mode

### ISSUE THREAD

**Issue by mirix** [MKuranowski/pyroutelib3#31]
Hello,

Is there a way to redefine the transport mode without hacking types.py? 

For instance, I have noticed that foot mode avoids cycleways at all costs. I guess I can easily add it as a possibility to types.py but I would rather have it redefined on my own scripts.

**Comment by MKuranowski** [comment]
The `transport` parameter of the constructor of both Router and Datastore also accept a dictionary. See <https://github.com/MKuranowski/pyroutelib3/wiki/Datastore#initializing>

**Comment by mirix** [comment]
It works, thank you.
