### ISSUE TITLE
HTTP Error 509: Bandwidth Limit Exceeded

### ISSUE THREAD

**Issue by DouglasJR1** [MKuranowski/pyroutelib3#32]
Hello @MKuranowski,

I use flask with folium and pyroutelib3. When I try to get coordinates with a car between two cities like in France : **"Paris"** and **"Lyon"** I have errors "HTTP Error 509: Bandwidth Limit Exceeded" (see attached).
This error happen only between cities far from each other (with lots of coordinates).

I try to change SEARCH_LIMIT to reduce number of nodes like the issues #27 but nothing work 

Do you have any ideas ? 

Thank you

**Comment by DouglasJR1** [comment]
![capture errors](https://user-images.githubusercontent.com/97282142/195368727-f5a540bf-7039-4d58-b674-f4090fc223b5.png)

**Comment by MKuranowski** [comment]
Seems similar to #16, but partially through OSM just decided you've downloaded too many tiles per unit time. Try to reproduce with local file first, and possibly for inter-city car routing on a simpler graph (see #26).

**Comment by MKuranowski** [comment]
Closed due to inactivity
