### ISSUE TITLE
Feature Request - Render Route Line on the Right Side of Non-One-Way Roads

### ISSUE THREAD

**Issue by DomeQdev** [MKuranowski/pyroutelib3#33]
I would like to request a new feature that allows the rendering of route lines on the right side of non-one-way roads. 
This feature would help resolve the issue of overlapping route lines when a bus, for example, travels along the same road segment multiple times.
![image](https://github.com/MKuranowski/pyroutelib3/assets/45435431/92f01863-76ec-4d4e-bcad-b6fdccc5bded)

This is how Szczecin handles buses going multiple times along the same road:
![image](https://github.com/MKuranowski/pyroutelib3/assets/45435431/08b67264-c432-4495-8f30-1975f326dc06)

**Comment by MKuranowski** [comment]
Good luck with that.

pyroutelib3 doesn't render anything. pyroutelib3 just takes a graph (or creates one from OSM data) and returns a list of nodes of a cheapest path between two nodes.

Also, pyroutelib3 is country-agnostic, and "side of the road" depends on whether a particular region drives on the left or on the right. And even that is not enough, there are streets in some countries (particularly Brasil) which just drive on the opposite side: https://www.openstreetmap.org/way/93268229

This is a problem for the application using pyroutelib3, not pyroutelib3 itself.

---

And a note for WarsawGTFS, cause I'm assuming that's the use case here. GTFS solves overlapping shapes with shape_dist_traveled. Also, shape generation is already very time-consuming and trying to figure out overlapping segments and shifting them would increase the complexity even further, with a very small impact. That's simply not worth it.
